/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as LoginRouteImport } from './routes/login'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as AssignmentsIndexRouteImport } from './routes/assignments/index'
import { Route as AssignmentsAssignmentIdRouteImport } from './routes/assignments/$assignmentId'
import { Route as StudentsIndexRouteImport } from './routes/students/index'
import { Route as StudentsStudentIdRouteImport } from './routes/students/$studentId'
import { Route as SubjectsIndexRouteImport } from './routes/subjects/index'
import { Route as SubjectsSubjectIdRouteImport } from './routes/subjects/$subjectId'
import { Route as SubmissionsSubmissionIdRouteImport } from './routes/submissions/$submissionId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const AssignmentsIndexRoute = AssignmentsIndexRouteImport.update({
  id: '/assignments/',
  path: '/assignments/',
  getParentRoute: () => rootRouteImport,
} as any)
const AssignmentsAssignmentIdRoute = AssignmentsAssignmentIdRouteImport.update({
  id: '/assignments/$assignmentId',
  path: '/assignments/$assignmentId',
  getParentRoute: () => rootRouteImport,
} as any)
const StudentsIndexRoute = StudentsIndexRouteImport.update({
  id: '/students/',
  path: '/students/',
  getParentRoute: () => rootRouteImport,
} as any)
const StudentsStudentIdRoute = StudentsStudentIdRouteImport.update({
  id: '/students/$studentId',
  path: '/students/$studentId',
  getParentRoute: () => rootRouteImport,
} as any)
const SubjectsIndexRoute = SubjectsIndexRouteImport.update({
  id: '/subjects/',
  path: '/subjects/',
  getParentRoute: () => rootRouteImport,
} as any)
const SubjectsSubjectIdRoute = SubjectsSubjectIdRouteImport.update({
  id: '/subjects/$subjectId',
  path: '/subjects/$subjectId',
  getParentRoute: () => rootRouteImport,
} as any)
const SubmissionsSubmissionIdRoute = SubmissionsSubmissionIdRouteImport.update({
  id: '/submissions/$submissionId',
  path: '/submissions/$submissionId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/assignments/$assignmentId': typeof AssignmentsAssignmentIdRoute
  '/students/$studentId': typeof StudentsStudentIdRoute
  '/subjects/$subjectId': typeof SubjectsSubjectIdRoute
  '/submissions/$submissionId': typeof SubmissionsSubmissionIdRoute
  '/assignments/': typeof AssignmentsIndexRoute
  '/students/': typeof StudentsIndexRoute
  '/subjects/': typeof SubjectsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/assignments/$assignmentId': typeof AssignmentsAssignmentIdRoute
  '/students/$studentId': typeof StudentsStudentIdRoute
  '/subjects/$subjectId': typeof SubjectsSubjectIdRoute
  '/submissions/$submissionId': typeof SubmissionsSubmissionIdRoute
  '/assignments': typeof AssignmentsIndexRoute
  '/students': typeof StudentsIndexRoute
  '/subjects': typeof SubjectsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/assignments/$assignmentId': typeof AssignmentsAssignmentIdRoute
  '/students/$studentId': typeof StudentsStudentIdRoute
  '/subjects/$subjectId': typeof SubjectsSubjectIdRoute
  '/submissions/$submissionId': typeof SubmissionsSubmissionIdRoute
  '/assignments/': typeof AssignmentsIndexRoute
  '/students/': typeof StudentsIndexRoute
  '/subjects/': typeof SubjectsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/register'
    | '/assignments/$assignmentId'
    | '/students/$studentId'
    | '/subjects/$subjectId'
    | '/submissions/$submissionId'
    | '/assignments/'
    | '/students/'
    | '/subjects/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/register'
    | '/assignments/$assignmentId'
    | '/students/$studentId'
    | '/subjects/$subjectId'
    | '/submissions/$submissionId'
    | '/assignments'
    | '/students'
    | '/subjects'
  id:
    | '__root__'
    | '/'
    | '/login'
    | '/register'
    | '/assignments/$assignmentId'
    | '/students/$studentId'
    | '/subjects/$subjectId'
    | '/submissions/$submissionId'
    | '/assignments/'
    | '/students/'
    | '/subjects/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LoginRoute: typeof LoginRoute
  RegisterRoute: typeof RegisterRoute
  AssignmentsAssignmentIdRoute: typeof AssignmentsAssignmentIdRoute
  StudentsStudentIdRoute: typeof StudentsStudentIdRoute
  SubjectsSubjectIdRoute: typeof SubjectsSubjectIdRoute
  SubmissionsSubmissionIdRoute: typeof SubmissionsSubmissionIdRoute
  AssignmentsIndexRoute: typeof AssignmentsIndexRoute
  StudentsIndexRoute: typeof StudentsIndexRoute
  SubjectsIndexRoute: typeof SubjectsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/assignments/': {
      id: '/assignments/'
      path: '/assignments'
      fullPath: '/assignments/'
      preLoaderRoute: typeof AssignmentsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/assignments/$assignmentId': {
      id: '/assignments/$assignmentId'
      path: '/assignments/$assignmentId'
      fullPath: '/assignments/$assignmentId'
      preLoaderRoute: typeof AssignmentsAssignmentIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/students/': {
      id: '/students/'
      path: '/students'
      fullPath: '/students/'
      preLoaderRoute: typeof StudentsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/students/$studentId': {
      id: '/students/$studentId'
      path: '/students/$studentId'
      fullPath: '/students/$studentId'
      preLoaderRoute: typeof StudentsStudentIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/subjects/': {
      id: '/subjects/'
      path: '/subjects'
      fullPath: '/subjects/'
      preLoaderRoute: typeof SubjectsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/subjects/$subjectId': {
      id: '/subjects/$subjectId'
      path: '/subjects/$subjectId'
      fullPath: '/subjects/$subjectId'
      preLoaderRoute: typeof SubjectsSubjectIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/submissions/$submissionId': {
      id: '/submissions/$submissionId'
      path: '/submissions/$submissionId'
      fullPath: '/submissions/$submissionId'
      preLoaderRoute: typeof SubmissionsSubmissionIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LoginRoute: LoginRoute,
  RegisterRoute: RegisterRoute,
  AssignmentsAssignmentIdRoute: AssignmentsAssignmentIdRoute,
  StudentsStudentIdRoute: StudentsStudentIdRoute,
  SubjectsSubjectIdRoute: SubjectsSubjectIdRoute,
  SubmissionsSubmissionIdRoute: SubmissionsSubmissionIdRoute,
  AssignmentsIndexRoute: AssignmentsIndexRoute,
  StudentsIndexRoute: StudentsIndexRoute,
  SubjectsIndexRoute: SubjectsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
