/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/healthz": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Liveness check */
        get: operations["healthz"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/register": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Create a teacher account */
        post: operations["register"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Log in */
        post: operations["login"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get the logged-in user */
        get: operations["getMe"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/dashboard": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Weekly activity summary for the logged-in teacher */
        get: operations["getDashboardSummary"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/assignments": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List assignments owned by the logged-in teacher */
        get: operations["listAssignments"];
        put?: never;
        /** Create an assignment under a subject */
        post: operations["createAssignment"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/assignments/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["AssignmentId"];
            };
            cookie?: never;
        };
        /** Get assignment detail (questions + files) */
        get: operations["getAssignment"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/assignments/{id}/files": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["AssignmentId"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Upload a PDF question paper for an assignment */
        post: operations["uploadAssignmentFile"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/assignments/{id}/submissions": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["AssignmentId"];
            };
            cookie?: never;
        };
        /** List submissions for an assignment */
        get: operations["listSubmissionsForAssignment"];
        put?: never;
        /** Create (or resume) a student's submission for an assignment */
        post: operations["createSubmission"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/submissions/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["SubmissionId"];
            };
            cookie?: never;
        };
        /** Get submission detail (pages, answer regions, composited doc) */
        get: operations["getSubmission"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/submissions/{id}/pages": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["SubmissionId"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Upload a scanned page for a submission */
        post: operations["uploadSubmissionPage"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/submissions/{id}/composited": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["SubmissionId"];
            };
            cookie?: never;
        };
        /** Get the composited PDF status / download link for a submission */
        get: operations["getSubmissionComposited"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/submissions/{id}/grade": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["SubmissionId"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Record a grade/feedback for a submission; syncs to Classroom when applicable */
        patch: operations["gradeSubmission"];
        trace?: never;
    };
    "/api/integrations/google/status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Whether the logged-in user has connected a Google account */
        get: operations["googleStatus"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/integrations/google": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Disconnect the logged-in user's Google account */
        delete: operations["googleDisconnect"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/integrations/google/teacher/auth-url": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Build the consent URL to connect Google Classroom as a teacher */
        get: operations["googleTeacherAuthUrl"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/integrations/google/courses": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List active Classroom courses the connected teacher teaches */
        get: operations["googleCourses"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/integrations/google/courses/{id}/coursework": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        /** List a course's coursework, flagging what's already imported */
        get: operations["googleCourseWork"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/integrations/google/import": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Import selected coursework as read-only assignments, syncing the roster */
        post: operations["googleImport"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/subjects": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List subjects — every subject for an admin, the teacher's own otherwise */
        get: operations["listSubjects"];
        put?: never;
        /** Create a subject */
        post: operations["createSubject"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/subjects/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["SubjectId"];
            };
            cookie?: never;
        };
        /** Get a subject and every student enrolled in it. A teacher gets 404 for a subject they don't own, same as if it didn't exist. */
        get: operations["getSubject"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/students": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List the logged-in teacher's student roster */
        get: operations["listStudents"];
        put?: never;
        /** Add a student to the roster (admin only) */
        post: operations["createStudent"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/students/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["StudentId"];
            };
            cookie?: never;
        };
        /** Get a student's enrolled subjects and work across assignments. A teacher only sees the slice that runs through subjects they own, and gets 404 if the student has no relationship to any of them. */
        get: operations["getStudent"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/students/{id}/enroll": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["StudentId"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Enroll a student into a subject (admin only) */
        post: operations["enrollStudent"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        ErrorResponse: {
            error: string;
        };
        /** @enum {string} */
        Role: "teacher" | "admin";
        User: {
            /** Format: uuid */
            id: string;
            email: string;
            role: components["schemas"]["Role"];
            /** Format: date-time */
            created_at: string;
        };
        RegisterRequest: {
            email: string;
            password: string;
        };
        LoginRequest: {
            email: string;
            password: string;
        };
        AuthResponse: {
            token: string;
            user: components["schemas"]["User"];
        };
        DailyActivity: {
            /** Format: date */
            date: string;
            weekday: string;
            pages_scanned: number;
            pending_submissions: number;
            pending_to_grade: number;
        };
        DashboardSummary: {
            today_pages_scanned: number;
            weekly_activity: components["schemas"]["DailyActivity"][];
            submitted_this_week: number;
            pending_this_week: number;
            submissions_this_week: number;
            pages_scanned_this_week: number;
            total_students: number;
            total_subjects: number;
            /** @description Assignments no student has submitted for yet. */
            pending_submissions: number;
            /** @description Assignments with a submission that hasn't been composited (graded) yet. */
            pending_to_grade: number;
        };
        /** @enum {string} */
        AssignmentStatus: "pending" | "expired" | "submitted" | "graded";
        Assignment: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            owner_id: string;
            title: string;
            /** Format: uuid */
            subject_id?: string | null;
            subject_name?: string | null;
            /** Format: date-time */
            due_date?: string | null;
            status: components["schemas"]["AssignmentStatus"];
            /** @enum {string} */
            source?: "manual" | "classroom";
            /** Format: date-time */
            created_at: string;
        };
        CreateAssignmentRequest: {
            title: string;
            /** Format: uuid */
            subject_id: string;
            /** Format: date-time */
            due_date?: string | null;
        };
        AssignmentFile: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            assignment_id: string;
            file_path: string;
            page_count: number;
            /** Format: date-time */
            created_at: string;
            download_url?: string;
        };
        Question: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            assignment_id: string;
            /** Format: uuid */
            assignment_file_id: string;
            question_number: number;
            has_defined_region: boolean;
            page_number?: number | null;
            region_x?: number | null;
            region_y?: number | null;
            region_width?: number | null;
            region_height?: number | null;
            /** Format: date-time */
            created_at: string;
        };
        AssignmentDetail: components["schemas"]["Assignment"] & {
            teacher_email: string;
            questions: components["schemas"]["Question"][];
            assignment_files: components["schemas"]["AssignmentFile"][];
        };
        /** @enum {string} */
        SubmissionStatus: "pending" | "processing" | "composited" | "failed";
        Submission: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            assignment_id: string;
            /** Format: uuid */
            student_id?: string | null;
            student_name: string;
            status: components["schemas"]["SubmissionStatus"];
            grade?: string | null;
            feedback?: string | null;
            /** Format: date-time */
            created_at: string;
        };
        SubmissionSummary: components["schemas"]["Submission"] & {
            page_count: number;
            answer_regions_done: number;
            answer_regions_total: number;
        };
        GradeRequest: {
            grade?: string | null;
            feedback?: string | null;
        };
        GradeResponse: {
            submission: components["schemas"]["Submission"];
            classroom_sync_error?: string;
        };
        GoogleStatus: {
            connected: boolean;
            google_email?: string;
        };
        GoogleAuthUrl: {
            url: string;
        };
        GoogleCourse: {
            ID: string;
            Name: string;
        };
        GoogleCourseWorkMaterial: {
            DriveFileID?: string;
            Title?: string;
        };
        GoogleCourseWork: {
            ID: string;
            CourseID: string;
            Title: string;
            Description?: string;
            DueDate?: string | null;
            Materials?: components["schemas"]["GoogleCourseWorkMaterial"][];
            already_imported: boolean;
        };
        GoogleImportRequest: {
            course_id: string;
            /** Format: uuid */
            subject_id: string;
            coursework_ids: string[];
        };
        GoogleImportResult: {
            imported: components["schemas"]["Assignment"][];
        };
        SubmissionPage: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            submission_id: string;
            page_number: number;
            raw_image_path: string;
            /** Format: date-time */
            created_at: string;
        };
        /** @enum {string} */
        AnswerRegionStatus: "pending" | "processing" | "done" | "failed";
        AnswerRegion: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            submission_id: string;
            /** Format: uuid */
            question_id: string;
            question_number: number;
            /** Format: uuid */
            source_page_id: string;
            status: components["schemas"]["AnswerRegionStatus"];
            crop_x: number;
            crop_y: number;
            crop_width: number;
            crop_height: number;
            extracted_ink_path?: string | null;
            error_message?: string | null;
            /** Format: date-time */
            created_at: string;
        };
        /** @enum {string} */
        CompositedDocumentStatus: "pending" | "generating" | "done" | "failed";
        CompositedDocument: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            submission_id: string;
            version: number;
            status: components["schemas"]["CompositedDocumentStatus"];
            file_path?: string | null;
            error_message?: string | null;
            /** Format: date-time */
            created_at: string;
        };
        SubmissionDetail: components["schemas"]["Submission"] & {
            pages: components["schemas"]["SubmissionPage"][];
            answer_regions: components["schemas"]["AnswerRegion"][];
            composited_document?: components["schemas"]["CompositedDocument"];
        };
        CreateSubmissionRequest: {
            student_name: string;
        };
        CreateSubmissionResponse: components["schemas"]["Submission"] & {
            page_count: number;
        };
        UploadPageResponse: {
            page: components["schemas"]["SubmissionPage"];
            answer_regions_queued: number;
        };
        CompositedStatusResponse: {
            status: components["schemas"]["CompositedDocumentStatus"];
            download_url?: string;
            error_message?: string;
        };
        Subject: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            owner_id: string;
            name: string;
            /** Format: date-time */
            created_at: string;
        };
        SubjectDetail: components["schemas"]["Subject"] & {
            students: components["schemas"]["Student"][];
        };
        CreateSubjectRequest: {
            name: string;
        };
        Student: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            owner_id: string;
            name: string;
            email?: string | null;
            /** Format: date-time */
            created_at: string;
        };
        StudentSummary: components["schemas"]["Student"] & {
            subjects: components["schemas"]["Subject"][];
        };
        CreateStudentRequest: {
            name: string;
            email?: string | null;
        };
        EnrollRequest: {
            /** Format: uuid */
            subject_id: string;
        };
        StudentWork: {
            /** Format: uuid */
            submission_id?: string;
            /** Format: uuid */
            assignment_id: string;
            assignment_title: string;
            subject_name?: string | null;
            status?: components["schemas"]["SubmissionStatus"] | null;
            page_count: number;
            answer_regions_done: number;
            answer_regions_total: number;
            /** Format: date-time */
            created_at?: string | null;
        };
        StudentDetail: components["schemas"]["Student"] & {
            subjects: components["schemas"]["Subject"][];
            submissions: components["schemas"]["StudentWork"][];
        };
    };
    responses: {
        /** @description Error */
        Error: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorResponse"];
            };
        };
    };
    parameters: {
        AssignmentId: string;
        SubmissionId: string;
        StudentId: string;
        SubjectId: string;
    };
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    healthz: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    register: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RegisterRequest"];
            };
        };
        responses: {
            /** @description Account created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuthResponse"];
                };
            };
            400: components["responses"]["Error"];
            409: components["responses"]["Error"];
        };
    };
    login: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoginRequest"];
            };
        };
        responses: {
            /** @description Logged in */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuthResponse"];
                };
            };
            401: components["responses"]["Error"];
        };
    };
    getMe: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Current user */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["User"];
                };
            };
            401: components["responses"]["Error"];
            404: components["responses"]["Error"];
        };
    };
    getDashboardSummary: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Summary */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DashboardSummary"];
                };
            };
            401: components["responses"]["Error"];
        };
    };
    listAssignments: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Assignments */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Assignment"][];
                };
            };
            401: components["responses"]["Error"];
        };
    };
    createAssignment: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateAssignmentRequest"];
            };
        };
        responses: {
            /** @description Assignment created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Assignment"];
                };
            };
            400: components["responses"]["Error"];
            401: components["responses"]["Error"];
        };
    };
    getAssignment: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["AssignmentId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Assignment detail */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AssignmentDetail"];
                };
            };
            400: components["responses"]["Error"];
            401: components["responses"]["Error"];
            404: components["responses"]["Error"];
        };
    };
    uploadAssignmentFile: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["AssignmentId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": {
                    /** Format: binary */
                    file: string;
                };
            };
        };
        responses: {
            /** @description File stored; page count parsed from the PDF */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AssignmentFile"];
                };
            };
            400: components["responses"]["Error"];
            401: components["responses"]["Error"];
            404: components["responses"]["Error"];
        };
    };
    listSubmissionsForAssignment: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["AssignmentId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Submissions */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SubmissionSummary"][];
                };
            };
            400: components["responses"]["Error"];
            401: components["responses"]["Error"];
            404: components["responses"]["Error"];
        };
    };
    createSubmission: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["AssignmentId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateSubmissionRequest"];
            };
        };
        responses: {
            /** @description Submission created or resumed */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CreateSubmissionResponse"];
                };
            };
            400: components["responses"]["Error"];
            401: components["responses"]["Error"];
            404: components["responses"]["Error"];
        };
    };
    getSubmission: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["SubmissionId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Submission detail */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SubmissionDetail"];
                };
            };
            400: components["responses"]["Error"];
            401: components["responses"]["Error"];
            404: components["responses"]["Error"];
        };
    };
    uploadSubmissionPage: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["SubmissionId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": {
                    page_number: number;
                    /** Format: binary */
                    page: string;
                };
            };
        };
        responses: {
            /** @description Page stored and answer-region extraction jobs queued */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UploadPageResponse"];
                };
            };
            400: components["responses"]["Error"];
            401: components["responses"]["Error"];
            404: components["responses"]["Error"];
        };
    };
    getSubmissionComposited: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["SubmissionId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Composited document status */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CompositedStatusResponse"];
                };
            };
            400: components["responses"]["Error"];
            401: components["responses"]["Error"];
            404: components["responses"]["Error"];
        };
    };
    gradeSubmission: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["SubmissionId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["GradeRequest"];
            };
        };
        responses: {
            /** @description Grade saved */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GradeResponse"];
                };
            };
            400: components["responses"]["Error"];
            401: components["responses"]["Error"];
            403: components["responses"]["Error"];
            404: components["responses"]["Error"];
        };
    };
    googleStatus: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Connection status */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GoogleStatus"];
                };
            };
            401: components["responses"]["Error"];
        };
    };
    googleDisconnect: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Disconnected */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            401: components["responses"]["Error"];
        };
    };
    googleTeacherAuthUrl: {
        parameters: {
            query: {
                redirect_uri: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Authorization URL */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GoogleAuthUrl"];
                };
            };
            400: components["responses"]["Error"];
            401: components["responses"]["Error"];
        };
    };
    googleCourses: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Courses */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GoogleCourse"][];
                };
            };
            401: components["responses"]["Error"];
            412: components["responses"]["Error"];
            502: components["responses"]["Error"];
        };
    };
    googleCourseWork: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Coursework */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GoogleCourseWork"][];
                };
            };
            401: components["responses"]["Error"];
            412: components["responses"]["Error"];
            502: components["responses"]["Error"];
        };
    };
    googleImport: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["GoogleImportRequest"];
            };
        };
        responses: {
            /** @description Imported assignments */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GoogleImportResult"];
                };
            };
            400: components["responses"]["Error"];
            401: components["responses"]["Error"];
            412: components["responses"]["Error"];
        };
    };
    listSubjects: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Subjects */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Subject"][];
                };
            };
            401: components["responses"]["Error"];
        };
    };
    createSubject: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateSubjectRequest"];
            };
        };
        responses: {
            /** @description Subject created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Subject"];
                };
            };
            400: components["responses"]["Error"];
            401: components["responses"]["Error"];
            409: components["responses"]["Error"];
        };
    };
    getSubject: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["SubjectId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Subject detail */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SubjectDetail"];
                };
            };
            400: components["responses"]["Error"];
            401: components["responses"]["Error"];
            404: components["responses"]["Error"];
        };
    };
    listStudents: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Students */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StudentSummary"][];
                };
            };
            401: components["responses"]["Error"];
        };
    };
    createStudent: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateStudentRequest"];
            };
        };
        responses: {
            /** @description Student created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Student"];
                };
            };
            400: components["responses"]["Error"];
            401: components["responses"]["Error"];
            403: components["responses"]["Error"];
            409: components["responses"]["Error"];
        };
    };
    getStudent: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["StudentId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Student detail */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StudentDetail"];
                };
            };
            400: components["responses"]["Error"];
            401: components["responses"]["Error"];
            404: components["responses"]["Error"];
        };
    };
    enrollStudent: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["StudentId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["EnrollRequest"];
            };
        };
        responses: {
            /** @description Student's enrolled subjects after enrolling */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Subject"][];
                };
            };
            400: components["responses"]["Error"];
            401: components["responses"]["Error"];
            403: components["responses"]["Error"];
            404: components["responses"]["Error"];
        };
    };
}
